name: Module CI

on:
  workflow_dispatch:
    inputs:
      opendaq-ref:
        description: "openDAQ SDK commit, branch or tag"
        required: false
        default: ""
  pull_request:

jobs:
  call-opendaq-modules-ci:
    name: Call module CI
    uses: openDAQ/actions/.github/workflows/reusable-module-ci.yml@jira/TBBAS-3013-resusable-workflow-ci-module
    with:
      opendaq-ref: ${{ github.event.inputs.opendaq-ref || '' }}
      packages: >
        [
          {
            "runners": ["ubuntu-*"],
            "packages": {"apt": ["libpcap-dev"]}
          }
        ]
